export enum PaymentStatus {
    PENDENTE = 'PAGAMENTO PENDENTE',
    REALIZADO = 'VER COMPROVANTE',
    CANCELADO = 'INSCRIÇÃO CANCELADA',
    EXPIRADO = 'PAGAMENTO EXPIRADO',
    REJEITADO = 'PAGAMENTO REJEITADO',
    PROCESSANDO = 'PROCESSANDO PAGAMENTO',
    GRATUITO = 'INSCRIÇÃO GRATUITA',
  }

  